VERSION = 0.1.0

PREFIX = /usr
MANPREFIX = $(PREFIX)/share/man

CPPFLAGS := $(CFLAGS) -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_XOPEN_SOURCE=700 -D_FILE_OFFSET_BITS=64
CFLAGS   := $(CFLAGS) -std=c99 -Wall -pedantic
LDFLAGS  := $(CFLAGS) -s
